### ISSUE TITLE
hcache -top 5的结果和 直接 hcache file的结果让人疑惑

### ISSUE THREAD

**Issue by kadn** [silenceshell/hcache#16]
我先是  ./hcache -top 5 了一个结果，我看到最大的文件是大概23M， 
![image](https://user-images.githubusercontent.com/15666774/129402082-b7abd890-75e2-4664-81dd-07e65e3af58a.png)

之后我用 dd命令生成了一个23M的文件 good
然后我看到这个good这个文件被缓存了100%
![image](https://user-images.githubusercontent.com/15666774/129402022-b48a14e0-49fd-4ab0-9362-111de7623399.png)

接着，我再次使用 ./hcache -top 5命令，没有在里面找到  good这个文件，我感觉很奇怪
![image](https://user-images.githubusercontent.com/15666774/129402153-e5872713-b0db-4042-bab7-e5c4e8061c89.png)

**Comment by silenceshell** [comment]
hcache top command now only shows cached files in user space, while the `good` file created by dd is cached in kernel space.

**Comment by wufan618223** [comment]
by the way, do you know any suitable tool can show page cache in kernel space?

**Comment by silenceshell** [comment]
hcahce(or pcstat) could show cache in kernel space, if you specify the file name. I am not sure there are other tools could show all cache files in kernel space.
hcache top command shows only cache in user space is because it get processes info from user space and thus to get cache files..
