### ISSUE TITLE
build error in arm64 ubuntu20.04 

### ISSUE THREAD

**Issue by xinjiyier** [silenceshell/hcache#19]
![image](https://user-images.githubusercontent.com/18064887/133609243-0cd6d2c3-0ce9-45db-82af-8d4f04c7747a.png)
![image](https://user-images.githubusercontent.com/18064887/133609280-e63017da-755e-4b5f-9f5b-98c51de40f54.png)

cpu 和系统信息如上图所示，报错信息如下：

![image](https://user-images.githubusercontent.com/18064887/133609418-06fe7064-0830-43fc-ad00-1845259efd51.png)

修改了  Makefile
'''
ubuntu@166:~/xiaoping.chen/hcache-master$ cat Makefile 
build:
	GOPROXY=https://**_goproxy.io_**  GOARCH="**_arm64_**" GOOS="linux" go build
'''

期待您的回复，谢谢。

**Comment by movie0125** [comment]
参考问题 #6 
目前pcstat 项目没有人维护了，最近我会通过vender方式修改这个bug

**Comment by silenceshell** [comment]
> 参考问题 #6
> 目前pcstat 项目没有人维护了，最近我会通过vender方式修改这个bug

[#30](https://github.com/tobert/pcstat/pull/30) has been merged, would you help to fix this issue? Thanks.

**Comment by movie0125** [comment]
已解决
