### ISSUE TITLE
Please explain the real meaning of the field；Special thanks

### ISSUE THREAD

**Issue by DearZh** [silenceshell/hcache#4]
What do these output fields mean?（ 想请问一下，这些输出字段的真正含义是什么？）

| Name        | Size (bytes)   | Pages      | Cached    | Percent |

**Comment by silenceshell** [comment]
Name: cache file name
Size: cache file size
Pages: cache file pages(in 4096 Bytes)
Cached: Pages in cache
Percent: ${Cached}/${Pages}
