### ISSUE TITLE
arm类型linux机器 bin 文件获取问题

### ISSUE THREAD

**Issue by tuouo** [silenceshell/hcache#5]
当前 readme文件中的Download 给出的bin 文件不能在arm类型的机器下使用，看起来是x86的

在Building 的 make build 这一步，出现 
go: github.com/tobert/pcstat@v0.0.0-20170528024208-91a7346e5b46: Get "https://gocenter.io/github.com/tobert/pcstat/@v/v0.0.0-20170528024208-91a7346e5b46.mod": dial tcp 35.230.74.213:443: i/o timeout
经过分析，应该是build的机器需要连接互联网实际上却连不上导致。

那么请问如何获取 arm类型linux机器 bin 文件， 或者如何在本地build（连不上互联网的情况下）

**Comment by silenceshell** [comment]
暂不提供，您找个能联网的机器build下吧
