### ISSUE TITLE
在Debian10 golang=2:1.14\~1\~bpo10+1 arm64设备上编译失败

### ISSUE THREAD

**Issue by USED255** [silenceshell/hcache#6]
输出如下
>$go build
```
# github.com/tobert/pcstat
../go/pkg/mod/github.com/tobert/pcstat@v0.0.0-20170528024208-91a7346e5b46/mnt_ns_linux.go:66:30: undefined: SYS_SETNS
```

**Comment by movie0125** [comment]
需要升级pcstat版本，我已经在提交patch

**Comment by movie0125** [comment]
https://github.com/tobert/pcstat/pull/30

**Comment by movie0125** [comment]
上游已经有修复patch了

**Comment by silenceshell** [comment]
@USED255 Sorry for the late response.
Would you like to build the current master branch on arm64? According to @movie0125 , this will be fixed after #15 merged.

**Comment by movie0125** [comment]
@silenceshell @USED255 
When the upstream `pcstat` [#30](https://github.com/tobert/pcstat/pull/30) is fixed, I will introduce the new version
I've tested it and it works.

**Comment by movie0125** [comment]
已解决
