### ISSUE TITLE
建议增加输出统计功能

### ISSUE THREAD

**Issue by qbit-git** [silenceshell/hcache#7]
我在用你开发 Linux Cache 查看工具 hcache，很好用的一个工具。
希望能增加统计总量的功能，类似下面的样子。
![image](https://user-images.githubusercontent.com/61911047/99748763-19621580-2b18-11eb-97ef-e8170762b1d3.png)

**Comment by silenceshell** [comment]
Would you like to submit a PR to support this feature?

**Comment by movie0125** [comment]
I want to try

**Comment by silenceshell** [comment]
> I want to try

Thanks. Look forward for your PR

**Comment by movie0125** [comment]
My idea is to add statistical rows in the following scenarios
1. top
2. unicode
3. plain

Several other scenarios do not need to add statistical rows
1. json
2. histo
3. terse

**Comment by movie0125** [comment]
#22 已处理
